name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: etiennedaubanay/youtube-dl-test:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps : 
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      
      - name: Push to Dockerhub
        run: |
          docker login -u etiennedaubanay -p ks76WNGWw25V6p8
          docker push $IMAGE_NAME

 
